environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous_integration\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

# Test only two environments to speed up CI time
#      PYTHON_VERSION: "3.4"
#      PYTHON_ARCH: "32"

#      PYTHON_VERSION: "2.7"
#      PYTHON_ARCH: "64"

#    - PYTHON_VERSION: "3.4"
#      PYTHON_ARCH: "64"

install:
    #SET PATH=C:\mingw64\bin;%PATH%
    #Use the pre-installed Miniconda for the desired arch
  - ps: if($env:PYTHON_ARCH -eq '32') {
      $env:path="C:\msys64\mingw\bin;C:\Miniconda;C:\Miniconda\Scripts;C:Miniconda\Library\bin;$($env:path)"
      }
      else {
          $env:path="C:\msys64\mingw64\bin;C:\Miniconda-x64;C:\Miniconda-x64\Scripts;C:Miniconda-x64\Library\bin;$($env:path)"
      }
  - C:\msys64\usr\bin\bash -lc "mingw-get install gdb"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S gcc "

  # DEBUGGING
  #- "SET PATH"
  #- "python --version"
  #- "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  #- "conda info"
  #- "conda list"

  # Create and activate a conda environment with the desired Python version
  - "conda update --yes --quiet conda"
  - "conda create --yes --quiet -n matrix_env python=%PYTHON_VERSION%"
  - "activate matrix_env"

  # Install PyTMatrix dependecies
  - "conda install -y -q numpy scipy nose "

  # Check that we have the expected version and architecture for Python
  # in the conda environment
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "conda list"

  # build pytmatrix
  - "%CMD_IN_ENV% python setup.py build_ext -i"

build: false

test_script:
  # run the unit tests
  #- "python -c \"import nose; nose.main()\" -v"
